# Learned ID embeddings, each feeding a layer below
TYPE_EMBEDDING_OUTPUT_DIM = 16
MOVE_EMBEDDING_OUTPUT_DIM = 64
SPECIES_EMBEDDING_OUTPUT_DIM = 64
ITEM_EMBEDDING_OUTPUT_DIM = 32
ABILITY_EMBEDDING_OUTPUT_DIM = 32

# What each embedding layer puts out
MOVE_LAYER_OUTPUT_DIM = 64
POKEMON_EMBEDDING_OUTPUT_DIM = 256
PLAYER_LAYER_OUTPUT_DIM = 128
FIELD_LAYER_OUTPUT_DIM = 64
HISTORY_LAYER_OUTPUT_DIM = 128

TRANSFORMER_DIM = 256
TRANSFORMER_HEADS = 8
TRANSFORMER_LAYERS = 4
TRANSFORMER_FF_DIM = 1024
